### PR TITLE
Minor fixes/improvements in dg-common 

### PR DESCRIPTION
**Pull request by SamerAdra**
Minor fixes/improvements in dg-common

### CODE REVIEW

**Comment by bryantrobbins** [comment]
@Brijeshrpatel9 Mr Scala, can you please take a look?

If it looks good to you, let's merge.

**Comment by mibrahim** [comment]
@Brijeshrpatel9 @aosama  can you please review ?

**Comment by SamerAdra** [comment]
@aosama, the ReflectionHelper changes are just for you, because of that use case case we discussed where we needed to take a string value and call a setter having a parameter of a parameterized type (e.g., an Option[Short]). Plain-old Java reflection was telling us the setter type in this example was Option[Object] thanks to type erasure (grrr), but the Scala compiler hides some type metadata in the compiled output and so we can get around this and learn the type so we can convert the string to the proper type before calling the setter by reflection.
Before the workaround was to hardcoded a new method override for each setter we wanted to call by reflection, with the new method taking in a string, doing the conversion, and setting the field value. Now we don't have to do that anymore!

**Comment by mibrahim** [comment]
@aosama Just to clarify, is his current code acceptable as it is ? If not,
can you just list the recommended changes?

**Comment by mibrahim** [comment]
Retracting, misunderstood.

**Comment by aosama** [comment]
looks ok to merge

**Pull request merged**
