### PR TITLE
Update DG_Boundary.rst

### PR DESCRIPTION
**Pull request by leeny324**
Fixed the decimal example to remove positive values. Added documentation for decimal, varchar, and date.

### CODE REVIEW

**Comment by mibrahim** [comment]
@leeny324 can you check why is the test failing ? can you check plz

**Comment by leeny324** [comment]
Looking into this. I didn't (mean to) make any code changes, so not sure why core build failed.

**Comment by leeny324** [comment]
It looks like the failure is coming from DataConsumerTest.java. Not sure why this is coming up why my commit. Can someone look into this?


testSendRequestFromWriter(org.finra.datagenerator.consumer.DataConsumerTest)  Time elapsed: 5.015 sec  <<< FAILURE!
java.lang.AssertionError: expected:<5> but was:<0>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:743)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:555)
        at org.junit.Assert.assertEquals(Assert.java:542)
        at org.finra.datagenerator.consumer.DataConsumerTest.testSendRequestFromWriter(DataConsumerTest.java:260)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
...
...
...

Results :

Failed tests:   testSendRequestSync(org.finra.datagenerator.consumer.DataConsumerTest): expected:<[test1]> but was:<[]>
  testSendRequestNoHandling(org.finra.datagenerator.consumer.DataConsumerTest): expected:<[test1]> but was:<[]>
  testSendRequestFromWriter(org.finra.datagenerator.consumer.DataConsumerTest): expected:<5> but was:<0>

Tests run: 192, Failures: 3, Errors: 0, Skipped: 0

**Comment by leeny324** [comment]
Ran all tests a few more times and am seeing that they are now passing. Maybe just flaky test execution.

**Comment by bryantrobbins** [comment]
These are only doc changes. Will merge and deal with flaky test later...

Thanks Nate!

**Comment by SamerAdra** [comment]
I have a dependent project that builds this from source, which build is failing due to this unit test flakiness. I will ignore it in my fork for now, but in the future I would appreciate, if we can't fix the unit tests, to mark them as ignore so we would still have a working build. Better yet if we could hold off on merging a PR until the tests all pass consistently.

**Comment by mibrahim** [comment]
Which unit tests are failing ?

**Comment by SamerAdra** [comment]
NegativeBoundHiveDateTest: lowerBoundTest2 (expected:<201[6-01-01]> but was:<201[5-12-29]>)
DataConsumerTest: testSendRequestNoHandling, testSendRequestSync, testSendRequestFromWriter

**Comment by Brijeshrpatel9** [comment]
Same Test is failing in my pull request.

**Comment by leeny324** [comment]
I know what's wrong with the test and will fix it.

**Comment by leeny324** [comment]
Fixed the code and created a PR.

**Pull request merged**
